# Youtube - Trending Video Analytics Reviewer
## Data Analytics with Python Course - Final Assessment
## Data Collection and Cleaning Part 1 of 2
submitted by: Ramon (Monch) Mercader

Please use README.md and Project_Backgroun.md files for more information on how to use this file.<br>

In [1]:
#Imported libraries
import os
import glob
import requests
import numpy as np
import pandas as pd
import datetime
from collections import Counter
print("all items imported") #Using this as a status to indicate that all the imports are completed

all items imported

In [2]:
#Housekeeping, check your current working directory and make sure you are inside Final_Assessment (or the main directory with datasets folder)
#You will need to use the output of this cell as your path in the next cell
#The folder should have the files and the datasets folder inside the current working directory
os.getcwd()

'C:\\Users\\monch.mercader\\Python\\Data_Analytics\\Module 1\\Final_Assessment'

## Australia Youtube Data section

In [3]:
#Collect all AU data and concatenate into AU dataframe
#Use the path above and add /datasets
#This uses an absolute path and os.path.join to make it OS independent

#For Macs path, replace the path below to your own:
#path = r'//Users/monchmercader/Python/Data_Analytics/Module 1/Final_Assessment/datasets'

#For Windows path, replace the path below to your own:
path = r'C:\Users\monch.mercader\Python\Data_Analytics\Module 1\Final_Assessment\datasets'
all_AU_files = glob.glob(os.path.join(path, "????????_AU_videos.csv"))     
df_from_each_AU_file = (pd.read_csv(f) for f in all_AU_files)
Total_AU_df = pd.concat(df_from_each_AU_file, ignore_index=True)

In [4]:
#Checking if the above operation was successful, and how many entries there are
Total_AU_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   video_id           1200 non-null   object
 1   title              1200 non-null   object
 2   publishedAt        1200 non-null   object
 3   channelId          1200 non-null   object
 4   channelTitle       1200 non-null   object
 5   categoryId         1200 non-null   int64
 6   trending_date      1200 non-null   object
 7   tags               1200 non-null   object
 8   view_count         1200 non-null   int64
 9   likes              1200 non-null   int64
 10  dislikes           1200 non-null   int64
 11  comment_count      1200 non-null   int64
 12  thumbnail_link     1200 non-null   object
 13  comments_disabled  1200 non-null   bool
 14  ratings_disabled   1200 non-null   bool
 15  description        1193 non-null   object
dtypes: bool(2), int64(5), object(9)
memory usage: 133.7+ KB

In [5]:
#Quick check on the top 3 entries
Total_AU_df.head(3)

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
0,aCIMYjqWxwA,"Australian Lamb: Make Lamb, Not Walls",2021-01-10T18:59:21Z,UC72mdTdZGMpLNG5kRfFVvaw,Australian Lamb,26,21.11.01,[none],132281,2339,114,0,https://i.ytimg.com/vi/aCIMYjqWxwA/default.jpg,True,False,Australia 2031. Our once united nation has bee...
1,snrPqH84tuc,I WAS ALL ALONE ON MY BIRTHDAY! (THEY FORGOT),2021-01-09T22:36:42Z,UC56D-IHcUvLVFTX_8NpQMXg,Brent Rivera,24,21.11.01,[none],3323919,226939,2788,41783,https://i.ytimg.com/vi/snrPqH84tuc/default.jpg,False,False,LIKE THIS VIDEO TO WISH ME A HAPPY BIRTHDAY :)...
2,sJn8dG9iSaw,Among Us Logic 13 | Cartoon Animation,2021-01-10T00:00:08Z,UCToxKVrkEuAONR4rFIJ_DyQ,GameToons,1,21.11.01,among us|among us logic|animation|funny animat...,2494114,94922,2277,12744,https://i.ytimg.com/vi/sJn8dG9iSaw/default.jpg,False,False,They are AMONG US skin pack ➡️ https://cutt.ly...

In [6]:
#Showing the columns for the dataframe
Total_AU_df.columns

Index(['video_id', 'title', 'publishedAt', 'channelId', 'channelTitle',
       'categoryId', 'trending_date', 'tags', 'view_count', 'likes',
       'dislikes', 'comment_count', 'thumbnail_link', 'comments_disabled',
       'ratings_disabled', 'description'],
      dtype='object')

In [7]:
#Filter categories to the most relevant, categoryId: 19 - Travel & Events, 21 - Video blogging, 22 - People & Blogs, 26 - How To & Style, 37 Family)
#Passing into a new filtered dataframe
Total_AU_df_filtered = Total_AU_df.drop(Total_AU_df[(Total_AU_df['categoryId'] != 19) & (Total_AU_df['categoryId'] != 21) 
                                                    & (Total_AU_df['categoryId'] != 22) & (Total_AU_df['categoryId'] != 26) 
                                                    & (Total_AU_df['categoryId'] != 37)].index)

In [8]:
#Checking on how many entries are remaining
Total_AU_df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 186 entries, 0 to 1198
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   video_id           186 non-null    object
 1   title              186 non-null    object
 2   publishedAt        186 non-null    object
 3   channelId          186 non-null    object
 4   channelTitle       186 non-null    object
 5   categoryId         186 non-null    int64
 6   trending_date      186 non-null    object
 7   tags               186 non-null    object
 8   view_count         186 non-null    int64
 9   likes              186 non-null    int64
 10  dislikes           186 non-null    int64
 11  comment_count      186 non-null    int64
 12  thumbnail_link     186 non-null    object
 13  comments_disabled  186 non-null    bool
 14  ratings_disabled   186 non-null    bool
 15  description        182 non-null    object
dtypes: bool(2), int64(5), object(9)
memory usage: 22.2+ KB

In [9]:
#Filtering out duplicates: Since the raw CSV scrapes are collected daily, videos may be popular over a period of time. Therefore, it is necessary to filter out the duplicates, and retain the most recent occurance of the video_id.
#This can be done by first finding out how many duplicates a video_id has. 
#The lines below uses the video_id column to pivot and counts the number of instances it appears in the dataframe

dup_df = pd.DataFrame(Total_AU_df_filtered, columns= ['video_id'])

duplicates_df = dup_df.pivot_table(index=['video_id'], aggfunc='size')
print (duplicates_df)
#Copy one of the video IDs below and use it in the following cells to check

video_id
-K6E6U58zGE    2
2Al7H9AiN1A    1
48NAQCSnHdQ    1
4_Vp3FhrzTk    1
4eSkcCuliJE    4
              ..
rJ-FEfXzKIY    3
u-sobyCVGQE    3
ySkmrQYF1h8    2
z4FnDEYg2yw    5
zBZ4skqOm04    5
Length: 67, dtype: int64

In [12]:
#This is to check that the drop_duplicates action in the next cells keep the correct entry (highest video)
# Insert your selected video ID from above here: Total_AU_df_filtered.loc[Total_AU_df_filtered['video_id'] == '<INSERT VIDEO ID HERE>']
Total_AU_df_filtered.loc[Total_AU_df_filtered['video_id'] == 'zBZ4skqOm04']
#Take note of the largest view_count number for this video

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
207,zBZ4skqOm04,Are You Subscribed?,2021-01-11T22:11:32Z,UC4-79UOlP48-QNGgCko5p2g,MrBeast Shorts,22,21.13.01,[none],4983747,325828,2441,24518,https://i.ytimg.com/vi/zBZ4skqOm04/default.jpg,False,False,Click that subscribe button because you might ...
408,zBZ4skqOm04,Are You Subscribed?,2021-01-11T22:11:32Z,UC4-79UOlP48-QNGgCko5p2g,MrBeast Shorts,22,21.14.01,[none],5374234,347927,2657,25633,https://i.ytimg.com/vi/zBZ4skqOm04/default.jpg,False,False,Click that subscribe button because you might ...
638,zBZ4skqOm04,Are You Subscribed?,2021-01-11T22:11:32Z,UC4-79UOlP48-QNGgCko5p2g,MrBeast Shorts,22,21.15.01,[none],6058428,377721,3012,27299,https://i.ytimg.com/vi/zBZ4skqOm04/default.jpg,False,False,Click that subscribe button because you might ...
923,zBZ4skqOm04,Are You Subscribed?,2021-01-11T22:11:32Z,UC4-79UOlP48-QNGgCko5p2g,MrBeast Shorts,22,21.18.01,[none],6618435,397401,3218,28142,https://i.ytimg.com/vi/zBZ4skqOm04/default.jpg,False,False,Click that subscribe button because you might ...
1139,zBZ4skqOm04,Are You Subscribed?,2021-01-11T22:11:32Z,UC4-79UOlP48-QNGgCko5p2g,MrBeast Shorts,22,21.19.01,[none],6649757,398236,3228,28193,https://i.ytimg.com/vi/zBZ4skqOm04/default.jpg,False,False,Click that subscribe button because you might ...

In [19]:
#This uses the drop method to remove the duplicates under the video_id column, and to keep the last instance. 
Final_AU_df = Total_AU_df_filtered.drop_duplicates(subset=['video_id'], keep='last')

In [20]:
#Quick check on how many entries remain after filtering duplicates
Final_AU_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 67 entries, 162 to 1198
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   video_id           67 non-null     object
 1   title              67 non-null     object
 2   publishedAt        67 non-null     object
 3   channelId          67 non-null     object
 4   channelTitle       67 non-null     object
 5   categoryId         67 non-null     int64
 6   trending_date      67 non-null     object
 7   tags               67 non-null     object
 8   view_count         67 non-null     int64
 9   likes              67 non-null     int64
 10  dislikes           67 non-null     int64
 11  comment_count      67 non-null     int64
 12  thumbnail_link     67 non-null     object
 13  comments_disabled  67 non-null     bool
 14  ratings_disabled   67 non-null     bool
 15  description        66 non-null     object
dtypes: bool(2), int64(5), object(9)
memory usage: 8.0+ KB

In [21]:
Final_AU_df.head(3)

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
162,S6aXAwYT6nY,MY LAST PREGNANCY UPDATE ON THE TWINS | OUR UL...,2021-01-04T20:53:06Z,UC_0mlge_fLewbr5P8YEL2tA,THE WEISS LIFE,26,21.11.01,pregnancy update on the twins!|unexpected news...,199889,9208,309,0,https://i.ytimg.com/vi/S6aXAwYT6nY/default.jpg,True,False,Don't forget to subscribe! http://www.youtube....
171,4_Vp3FhrzTk,EATING MASSIVE SEA URCHIN,2020-12-17T03:44:22Z,UCMyOj6fhvKFMjxUCp3b_3gA,Nick DiGiovanni,22,21.11.01,[none],3422355,80402,5955,3326,https://i.ytimg.com/vi/4_Vp3FhrzTk/default.jpg,False,False,Uni is certainly not for everybody. It's a bla...
172,2Al7H9AiN1A,Positive 2021 Goals! 12 Unique Ab Exercises & ...,2020-12-31T04:41:05Z,UCAHufvd02viJSRdt3ojdPOg,Sarahs Day,22,21.11.01,new years resolution|goals|setting goals|new y...,455438,26518,190,1028,https://i.ytimg.com/vi/2Al7H9AiN1A/default.jpg,False,False,SWEAT IT TO SHRED IT EBOOK FITNESS GUIDES!!htt...

In [22]:
#To confirm that the process was successful, use the video ID you selected and confirm that the highest view count is the only entry that remains 
Final_AU_df.loc[Final_AU_df['video_id'] == 'zBZ4skqOm04']

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
1139,zBZ4skqOm04,Are You Subscribed?,2021-01-11T22:11:32Z,UC4-79UOlP48-QNGgCko5p2g,MrBeast Shorts,22,21.19.01,[none],6649757,398236,3228,28193,https://i.ytimg.com/vi/zBZ4skqOm04/default.jpg,False,False,Click that subscribe button because you might ...

In [23]:
#Check if there are any missing values 
Final_AU_df.isna()
#True are missing values, False are populated/legitimate values

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
162,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
171,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
172,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
178,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
183,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1149,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1158,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1166,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1172,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1198,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#Write the current dataframe to a new TOTAL CSV file YR.MONTH.DAY_TOTAL_COUNTRY.CSV
Final_AU_df.to_csv(r'C:\Users\monch.mercader\Python\Data_Analytics\Module 1\Final_Assessment\datasets\YR.MONTH.DAY_TOTAL_AU.csv')

#'Path where you want to store the exported CSV file\File Name.csv')

In [ ]:
#Repeat for all other countries

In [ ]:
#Sorting out view_count and passing it to a new Dataframe: Total_AU_viewcountsort
Total_AU_viewcountsort = new_df.sort_values(by=['view_count'])
new_df['view_count']
#Total_AU_viewcountsort['view_count']

In [ ]:

import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.plot(new_df['view_count'])
plt.show()

In [ ]:
fig = plt.figure(figsize=(25,12), dpi=300, facecolor='gray')

plt.hist(x=new_df['view_count'], color='green', rwidth=800, bins=80, histtype='stepfilled', alpha=0.4)

#plt.hist(x=new_df['dislikes'], color='red', bins=80, histtype='stepfilled', alpha=0.4)
#plt.hist(x=new_df['likes'], color='cyan', bins=80, histtype='stepfilled', alpha=0.5)

plt.title('Total current views', fontdict={'fontsize': 20})
plt.xlabel('Total YYYYYYYYY')
plt.ylabel('Total XXXXXXXXXX')

# plt.show()

In [ ]:
#plt.hist(x=df['maxtemp'], color='red', bins=50, histtype='stepfilled', alpha=0.4)
#plt.hist(x=df['mintemp'], color='cyan', bins=50, histtype='stepfilled', alpha=0.5)
#plt.title('Maximum & Minimum Temperature - 2007-2017', fontdict={'fontsize': 15})
#plt.xlabel('Temperature Distribution in Celcius')
#plt.ylabel('Temperature Frequency in 10 Years')
# plt.show()